---
# tasks file for serverspec
- name: install ruby
  apt: name=ruby state=present
# to install community ,run: ansible-galaxy collection install community.general
- name: install serverspec
  community.general.gem: name={{ item }} state=present user_install=no 
  with_items:
   - rake
   - serverspec
