---
# tasks file for jenkins
- name: install jdk
  apt: name=java-1.8.0-openjdk-devel state=present

- name: download yum repository file of jenkins
  get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/apt/sources.list mode=0644

- name: import apt key
  apt_key : state=present key=https://pkg.jenkins.io/debian-stable/jenkins.io.key

- name: install jenkins
  apt: name=jenkins state=present

- name: start jenkins
  service: name=jenkins state=started enabled=yes
